spring :
   profiles:
     active:
     - dev
---
spring:
   profiles: dev #开发环境
   application:
        name:Eureka-config-atv-dev
---
spring:
   profiles: test #测试环境
   application:
        name:Eureka-config-atv-test